import { readFile, writeFile, mkdir, cp, rm } from 'node:fs/promises';
import { join } from 'node:path';
import { createSVGWindow } from 'svgdom';
import { SVG, registerWindow } from '@svgdotjs/svg.js';

const config = JSON.parse(await readFile('site.config.json', 'utf8'));
const businessName = String(config.name || 'Ana Maria').trim();
const phone = String(process.env.WHATSAPP || config.whatsapp || '').replace(/\D/g, '');
const siteUrl = String(config.siteUrl || process.env.SITE_URL || '').trim().replace(/\/+$/, '');
if (phone && !/^55\d{10,11}$/.test(phone)) throw new Error('WhatsApp deve incluir 55 + DDD + número, só dígitos.');
if (siteUrl) {
  const url = new URL(siteUrl);
  if (url.protocol !== 'https:' || url.pathname !== '/' || url.search || url.hash) throw new Error('siteUrl deve conter apenas a origem HTTPS do domínio.');
}

const esc = (value) => String(value).replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[char]);
const home = '/';
const family = '/plano-de-saude-familiar-fortaleza/';
const company = '/plano-de-saude-empresarial-fortaleza/';
const mei = '/plano-de-saude-mei-fortaleza/';
const breadcrumbNames = { [family]: 'Plano de saúde familiar', [company]: 'Plano de saúde empresarial', [mei]: 'Plano de saúde para MEI' };
const detailHeroContent = {
  [family]: { highlight: 'compare opções.', badge: 'Para sua família' },
  [company]: { highlight: 'no Ceará.', badge: 'Para sua empresa' },
  [mei]: { highlight: 'compare opções.', badge: 'Para quem é MEI' },
};
const quoteMessage = 'Olá, Ana Maria! Gostaria de uma cotação de plano de saúde em Fortaleza.';
const contactHref = (message = quoteMessage) => phone ? `https://wa.me/${phone}?text=${encodeURIComponent(message)}` : '/#contato';
const target = phone ? ' target="_blank" rel="noopener noreferrer"' : '';
const button = (label, message, className = 'button button-primary') => `<a class="${className}" href="${contactHref(message)}"${target}>${label}<svg aria-hidden="true" viewBox="0 0 24 24" fill="none"><path d="M5 12h14m-6-6 6 6-6 6" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"/></svg></a>`;
const faq = (items) => `<div class="faq-list">${items.map(([q, a]) => `<details><summary>${q}<span aria-hidden="true">+</span></summary><p>${a}</p></details>`).join('')}</div>`;
const check = (items) => `<ul class="check-list">${items.map((item) => `<li><span aria-hidden="true">✓</span>${item}</li>`).join('')}</ul>`;

function speechBubbleSvg() {
  const window = createSVGWindow();
  registerWindow(window, window.document);
  const draw = SVG(window.document.documentElement).size(370, 320).viewbox(0, 0, 370, 320);
  draw.path('M 94 7 C 40 11 14 42 8 93 C 2 144 8 199 25 237 C 18 257 11 273 5 285 C 28 286 46 282 64 270 C 98 298 151 310 223 309 C 311 308 353 275 361 212 C 369 158 363 85 340 48 C 318 12 273 5 197 5 C 156 5 121 5 94 7 Z')
    .fill('#fff8ec')
    .stroke({ color: '#ffc45f', width: 4, linejoin: 'round' });
  return draw.svg();
}

function shell({ path, title, description, body, image = false }) {
  const canonical = siteUrl ? `<link rel="canonical" href="${esc(siteUrl + path)}">` : '';
  const ogUrl = siteUrl ? `<meta property="og:url" content="${esc(siteUrl + path)}">` : '';
  const ogImage = siteUrl && image ? `<meta property="og:image" content="${esc(siteUrl)}/assets/familia-fortaleza.webp">` : '';
  const schemaData = !siteUrl ? null : path === '/' ? { '@context': 'https://schema.org', '@graph': [{ '@type': 'WebSite', name: 'Planos de Saúde no Ceará e Fortaleza | Ana Maria', url: siteUrl + '/' }, { '@type': 'Person', name: businessName, url: siteUrl + '/' }] } : { '@context': 'https://schema.org', '@type': 'BreadcrumbList', itemListElement: [{ '@type': 'ListItem', position: 1, name: 'Início', item: siteUrl + '/' }, { '@type': 'ListItem', position: 2, name: breadcrumbNames[path] }] };
  const schema = schemaData ? `<script type="application/ld+json">${JSON.stringify(schemaData).replace(/</g, '\\u003c')}</script>` : '';
  return `<!doctype html>
<html lang="pt-BR">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="theme-color" content="#073e49">
  <meta name="robots" content="index,follow,max-image-preview:large">
  <title>${esc(title)}</title>
  <meta name="description" content="${esc(description)}">
  ${canonical}
  <meta property="og:type" content="website">
  <meta property="og:locale" content="pt_BR">
  <meta property="og:title" content="${esc(title)}">
  <meta property="og:description" content="${esc(description)}">
  ${ogUrl}${ogImage}
  <link rel="icon" href="/assets/favicon.svg" type="image/svg+xml">
  ${image ? '<link rel="preload" as="image" href="/assets/familia-fortaleza-mobile.webp" media="(max-width: 699px)"><link rel="preload" as="image" href="/assets/familia-fortaleza.webp" media="(min-width: 700px)">' : ''}
  <link rel="stylesheet" href="/assets/site.css">
  ${schema}
</head>
<body class="${image ? 'home-page' : 'detail-page'}">
  <a class="skip-link" href="#conteudo">Pular para o conteúdo</a>
  <header class="site-header">
    <div class="container header-inner">
      <a class="brand" href="/"><span class="brand-mark" aria-hidden="true"><svg viewBox="0 0 40 40" fill="none"><path d="M20 32 9 21C3 14 13 6 20 14c7-8 17 0 11 7L20 32Z" fill="currentColor"/></svg></span><span><strong>${esc(businessName)}</strong><small>PLANOS DE SAÚDE</small></span></a>
      <button class="menu-button" type="button" aria-label="Abrir menu" aria-expanded="false" aria-controls="menu-principal" data-menu-button><span></span><span></span><span></span></button>
      <nav id="menu-principal" class="main-nav" aria-label="Navegação principal" data-menu>
        <a href="/#opcoes">Tipos de plano</a><a href="/#como-funciona">Como funciona</a><a href="/#duvidas">Dúvidas</a><a href="/#contato">Contato</a>
        ${button('Pedir cotação', quoteMessage, 'button button-small button-primary nav-cta')}
      </nav>
    </div>
  </header>
  <main id="conteudo">${body}</main>
  <footer class="site-footer">
    <div class="container footer-grid">
      <div><a class="brand brand-light" href="/"><span class="brand-mark" aria-hidden="true"><svg viewBox="0 0 40 40" fill="none"><path d="M20 32 9 21C3 14 13 6 20 14c7-8 17 0 11 7L20 32Z" fill="currentColor"/></svg></span><span><strong>${esc(businessName)}</strong><small>PLANOS DE SAÚDE</small></span></a><p>Orientação para encontrar um plano de saúde que faça sentido para você, sua família ou seu negócio em Fortaleza, Ceará.</p></div>
      <div><h2>Navegue</h2><a href="/#opcoes">Tipos de plano</a><a href="/#como-funciona">Como funciona</a><a href="/#duvidas">Perguntas frequentes</a><a href="/#contato">Contato</a></div>
      <div><h2>Planos</h2><a href="${family}">Plano familiar</a><a href="${company}">Plano empresarial</a><a href="${mei}">Plano para MEI</a></div>
      <div><h2>Atendimento</h2><p>Fortaleza, Ceará<br>Atendimento e cotação online</p>${phone ? `<a class="footer-contact" href="${contactHref()}"${target}>Conversar pelo WhatsApp ↗</a>` : '<p class="setup-note">Canal de WhatsApp em configuração.</p>'}<a href="https://www.gov.br/ans/pt-br/acesso-a-informacao/guia-de-planos/guia-de-planos" target="_blank" rel="noopener noreferrer">Guia de Planos da ANS ↗</a></div>
    </div>
    <div class="container footer-bottom"><span>© ${new Date().getFullYear()} ${esc(businessName)}.</span><span>Informações sobre planos dependem das condições de cada operadora.</span></div>
  </footer>
  ${phone ? `<a class="whatsapp-float" href="${contactHref()}" target="_blank" rel="noopener noreferrer" aria-label="Conversar com Ana Maria pelo WhatsApp" title="Conversar pelo WhatsApp"><svg viewBox="0 0 32 32" fill="none" aria-hidden="true"><path d="M16 3.5a12.5 12.5 0 0 0-10.8 18.8L3.5 28.5l6.4-1.7A12.5 12.5 0 1 0 16 3.5Z" stroke="currentColor" stroke-width="2.2" stroke-linejoin="round"/><path d="M11.1 10.1c.5-.4 1-.3 1.3.2l1.5 2.3c.3.5.2.9-.2 1.3l-.7.7a11 11 0 0 0 4.4 4.4l.7-.7c.4-.4.8-.5 1.3-.2l2.3 1.5c.5.3.6.8.2 1.3-.8 1.2-2.3 1.7-3.8 1.2-3.6-1.2-7.6-5.2-8.8-8.8-.5-1.5 0-3 1.2-3.8Z" fill="currentColor"/></svg></a>` : `<div class="mobile-action">${button('Solicitar cotação', quoteMessage, 'button button-primary')}</div>`}
  <script src="/assets/site.js" defer></script>
</body>
</html>`;
}

const options = [
  { num: '01', icon: '♡', title: 'Plano de saúde familiar', text: 'Proteção para você e sua família, com opções que variam conforme faixa etária, cobertura, acomodação e rede de atendimento.', href: family, link: 'Ver planos familiares' },
  { num: '02', icon: '✳', title: 'Plano de saúde para MEI', text: 'Quem possui MEI ou outro CNPJ pode ter acesso a opções empresariais, conforme as regras de contratação de cada operadora.', href: mei, link: 'Ver planos para MEI' },
  { num: '03', icon: '▦', title: 'Plano de saúde empresarial', text: 'Soluções para empresas que desejam oferecer assistência à saúde para sócios, colaboradores e seus dependentes.', href: company, link: 'Ver planos empresariais' },
];

const homeBody = `
  <section class="hero" aria-labelledby="hero-title">
    <div class="container hero-grid">
      <div class="hero-copy"><p class="eyebrow eyebrow-light"><svg class="hero-pin" viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M12 22s7-7.1 7-13a7 7 0 1 0-14 0c0 5.9 7 13 7 13Z" fill="currentColor"/><circle cx="12" cy="9" r="2.5" fill="#07525b"/></svg>PLANOS DE SAÚDE NO CEARÁ</p><h1 id="hero-title">Planos de Saúde no Ceará e em Fortaleza: <em>compare suas opções</em></h1><p class="hero-lead">Encontrar um plano de saúde adequado depende da sua idade, cidade, tipo de contratação, rede de atendimento e orçamento.<br><br>Receba atendimento personalizado para comparar opções de plano de saúde em Fortaleza e no Ceará para você, sua família, MEI ou empresa.</p><div class="hero-actions">${button('Solicitar cotação', quoteMessage)}<a class="text-link text-link-light" href="#opcoes">Conhecer as opções <span aria-hidden="true">↗</span></a></div><div class="hero-foot"><span><span class="hero-foot-icon" aria-hidden="true"><svg viewBox="0 0 32 32" fill="none"><path d="M6 7h20v14H14l-7 5v-5H6V7Z" stroke="currentColor" stroke-width="2" stroke-linejoin="round"/><circle cx="11" cy="14" r="1.2" fill="currentColor"/><circle cx="16" cy="14" r="1.2" fill="currentColor"/><circle cx="21" cy="14" r="1.2" fill="currentColor"/></svg></span>Atendimento<br>personalizado</span><span><span class="hero-foot-icon" aria-hidden="true"><svg viewBox="0 0 32 32" fill="none"><circle cx="11" cy="11" r="4" fill="currentColor"/><circle cx="22" cy="12" r="3" fill="currentColor"/><path d="M3.5 26v-3a7.5 7.5 0 0 1 15 0v3H3.5Zm16 0v-2.5c0-2.1-.7-3.8-1.7-5.1A6.5 6.5 0 0 1 28.5 23v3h-9Z" fill="currentColor"/></svg></span>Diferentes<br>tipos de plano</span><span><span class="hero-foot-icon" aria-hidden="true"><svg viewBox="0 0 32 32" fill="none"><path d="m16 3 10 4v7c0 7.4-3.7 11.9-10 15-6.3-3.1-10-7.6-10-15V7l10-4Z" fill="currentColor"/><path d="m11 16 3.3 3.3L21.5 12" stroke="#07525b" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"/></svg></span>Cotação sem<br>compromisso</span></div></div>
      <div class="hero-visual"><span class="hero-swoosh" aria-hidden="true"></span><span class="hero-sparks" aria-hidden="true"></span><picture class="hero-family"><source media="(max-width: 699px)" srcset="/assets/familia-fortaleza-mobile.webp"><img src="/assets/familia-fortaleza.webp" alt="Três gerações de uma família reunidas em casa" width="1536" height="1024" fetchpriority="high"></picture><span class="hero-heart" aria-hidden="true"><svg viewBox="0 0 40 40" fill="none"><path d="M20 32 9 21C3 14 13 6 20 14c7-8 17 0 11 7L20 32Z" fill="currentColor"/></svg></span><img class="hero-character" src="/assets/ana-maria-hero.webp" alt="" width="1055" height="1490" decoding="sync" fetchpriority="high"><div class="visual-badge"><span class="badge-icon" aria-hidden="true">✳</span><span>Mais segurança e bem-estar<br><strong>para quem você ama.</strong></span></div></div>
      <div class="hero-speech"><p class="hero-speech-intro">Oi!<br><strong>Conte comigo</strong> <span aria-hidden="true">♥</span></p><p>Vou te ajudar a encontrar<br>o plano de saúde ideal<br>para você e sua família,<br>com mais clareza<br>e sem complicação.</p></div>
    </div>
  </section>
  <section class="quick-links" aria-label="Escolha por perfil"><div class="container quick-links-inner"><p>Qual plano combina com você?</p><a href="${family}">Pessoa e família <span aria-hidden="true">↗</span></a><a href="${company}">Empresa <span aria-hidden="true">↗</span></a><a href="${mei}">MEI <span aria-hidden="true">↗</span></a></div></section>
  <section class="section options-section" id="opcoes"><div class="container"><div class="section-heading"><div><p class="eyebrow">ESCOLHA COM TRANQUILIDADE</p><h2>Encontre o plano de saúde ideal para o seu perfil</h2></div><p>Existem diferentes formas de contratar um plano de saúde. Veja qual modalidade mais combina com o que você procura.</p></div><div class="option-grid">${options.map((o) => `<article class="option-card"><span class="card-num">${o.num}</span><span class="option-icon" aria-hidden="true">${o.icon}</span><h3>${o.title}</h3><p>${o.text}</p><a href="${o.href}" class="card-link">${o.link} <span aria-hidden="true">↗</span></a></article>`).join('')}</div><p class="section-note">A disponibilidade e as condições variam conforme a operadora, o tipo de contratação e o perfil do beneficiário.</p></div></section>
  <section class="section seo-content"><div class="container seo-content-inner"><p class="eyebrow">ESCOLHA COM INFORMAÇÃO</p><h2>Como escolher um plano de saúde no Ceará?</h2><p>Escolher um plano de saúde não significa simplesmente procurar a mensalidade mais barata.</p><p>No Ceará, as opções disponíveis podem variar de acordo com a cidade, idade dos beneficiários, quantidade de pessoas, tipo de contratação e rede de atendimento oferecida por cada produto.</p><p>Em Fortaleza, por exemplo, existem planos individuais ou familiares e também opções destinadas a MEI e empresas.</p><p>Antes de contratar, é importante comparar principalmente:</p><ul><li>Rede de hospitais, clínicas e laboratórios;</li><li>Cobertura oferecida pelo plano;</li><li>Atendimento na sua cidade;</li><li>Acomodação em enfermaria ou apartamento;</li><li>Existência ou não de coparticipação;</li><li>Períodos de carência;</li><li>Abrangência regional ou nacional;</li><li>Regras para inclusão de dependentes;</li><li>Valor da mensalidade de acordo com a faixa etária.</li></ul><p>A melhor escolha depende das necessidades de cada pessoa ou empresa. Por isso, uma cotação personalizada permite comparar opções compatíveis com o seu perfil antes da contratação.</p></div></section>
  <section class="section process-section" id="como-funciona"><div class="container process-grid"><div class="process-intro"><p class="eyebrow">DO PRIMEIRO CONTATO À ESCOLHA</p><h2>Como funciona a cotação do plano de saúde?</h2><p>A cotação considera seu perfil e as opções disponíveis para a modalidade de contratação desejada.</p>${button('Conversar sobre meu plano', 'Olá, Ana Maria! Quero entender as opções de plano de saúde no Ceará.', 'button button-outline')}</div><div class="step-list"><article><span>01</span><div><h3>Informe seu perfil</h3><p>Envie informações como idade dos beneficiários, cidade e tipo de plano que procura.</p></div></article><article><span>02</span><div><h3>Compare as opções</h3><p>São verificadas as alternativas disponíveis de acordo com o seu perfil e modalidade de contratação.</p></div></article><article><span>03</span><div><h3>Escolha com mais informação</h3><p>Compare cobertura, rede, condições e valores antes de decidir qual opção atende melhor às suas necessidades.</p></div></article></div></div></section>
  <section class="section guide-section" id="o-que-avaliar"><div class="container guide-grid"><div class="guide-art"><span class="art-sun" aria-hidden="true"></span><img class="guide-character" src="/assets/ana-maria-personagem.webp" alt="" width="800" height="1200" loading="lazy" decoding="async"><div class="guide-art-card"><span>O que observar</span><strong>O melhor plano é aquele que atende às suas necessidades.</strong></div><span class="art-circle art-circle-one" aria-hidden="true"></span><span class="art-circle art-circle-two" aria-hidden="true"></span></div><div class="guide-copy"><p class="eyebrow">ANTES DE CONTRATAR</p><h2>O que analisar antes de contratar um plano de saúde?</h2><div class="analysis-grid"><article><h3>Rede de atendimento</h3><p>Confira quais hospitais, clínicas, laboratórios e outros serviços fazem parte da rede do produto que você está considerando.</p></article><article><h3>Cobertura</h3><p>Existem diferentes tipos de cobertura. Analise quais serviços estão incluídos e se eles atendem às suas necessidades.</p></article><article><h3>Coparticipação</h3><p>Alguns planos possuem mensalidade associada à cobrança de coparticipação quando determinados serviços são utilizados. Compare as regras antes de decidir.</p></article><article><h3>Carência</h3><p>Os períodos de carência podem variar conforme o produto e a forma de contratação. As condições precisam ser verificadas na proposta apresentada pela operadora.</p></article></div><a class="text-link" href="#duvidas">Veja as dúvidas frequentes <span aria-hidden="true">↗</span></a></div></div></section>
  <section class="section local-section"><div class="container local-card"><div class="local-copy"><p class="eyebrow eyebrow-light">FORTALEZA E CEARÁ</p><h2>Planos de saúde em Fortaleza e outras cidades do Ceará</h2><p>Quem procura um plano de saúde no Ceará deve observar principalmente se o produto possui atendimento adequado na cidade onde pretende utilizar o plano.</p><p>Fortaleza concentra uma ampla oferta de hospitais, clínicas, laboratórios e diferentes modalidades de contratação. Para quem mora em outras cidades do Ceará, a disponibilidade de produtos e da rede assistencial pode ser diferente.</p><p>Por isso, ao solicitar uma cotação, informe sua cidade para verificar quais alternativas estão disponíveis para sua região.</p><ul class="local-profiles"><li>Individual ou familiar</li><li>MEI</li><li>Pequenas empresas</li><li>Empresas com vários beneficiários</li></ul>${button('Pedir uma cotação', quoteMessage, 'button button-cream')}</div><div class="local-illustration" aria-hidden="true"><span class="local-sun"></span><img class="local-character" src="/assets/ana-maria-personagem.webp" alt="" width="800" height="1200" loading="lazy" decoding="async"></div></div></section>
  <section class="section seo-content personal-section"><div class="container personal-copy"><p class="eyebrow">ATENDIMENTO PERSONALIZADO</p><h2>Atendimento personalizado para escolher seu plano</h2><p>Escolher um plano de saúde envolve diversas informações: rede, cobertura, valores, carências e regras de contratação.</p><p>Ana Maria oferece atendimento personalizado para entender o perfil de cada cliente e apresentar as opções disponíveis para comparação.</p><p>Assim, você pode analisar as alternativas antes de contratar e escolher com mais clareza.</p>${button('Falar com Ana Maria', quoteMessage, 'button button-primary')}</div></section>
  <section class="section faq-section" id="duvidas"><div class="container faq-grid"><div><p class="eyebrow">PERGUNTAS FREQUENTES</p><h2>Perguntas frequentes sobre planos de saúde no Ceará</h2><p>Condições específicas precisam ser confirmadas na proposta e no contrato de cada operadora.</p></div>${faq([
    ['Quanto custa um plano de saúde no Ceará?', 'O valor depende de fatores como idade dos beneficiários, cidade, modalidade de contratação, operadora, cobertura, acomodação e existência de coparticipação. Para saber o valor aplicável ao seu perfil é necessário fazer uma cotação.'],
    ['Qual é o melhor plano de saúde em Fortaleza?', 'Não existe um único plano que seja o melhor para todas as pessoas. A melhor escolha depende da rede que você deseja utilizar, orçamento, cobertura, idade dos beneficiários e modalidade de contratação.'],
    ['Posso contratar plano de saúde sem CNPJ?', 'Existem produtos destinados a pessoas físicas e famílias, dependendo da disponibilidade das operadoras. Quem possui CNPJ ou MEI também pode verificar opções de contratação empresarial.'],
    ['MEI pode contratar plano de saúde empresarial?', 'Existem planos empresariais que aceitam MEI, desde que sejam cumpridas as regras de elegibilidade definidas pela operadora para aquele produto.'],
    ['O que é coparticipação?', 'É uma modalidade em que, além da mensalidade, pode haver cobrança de um valor ou percentual relacionado à utilização de determinados serviços previstos no contrato.'],
    ['Plano de saúde tem carência?', 'Dependendo do produto e da modalidade de contratação, podem existir períodos de carência. As regras precisam ser verificadas nas condições específicas da proposta.'],
    ['Existem planos de saúde para outras cidades do Ceará?', 'A disponibilidade varia conforme a cidade, operadora e produto. Informe o município onde o plano será utilizado para verificar as alternativas disponíveis.'],
    ['Como solicitar uma cotação?', 'Informe a cidade, idade das pessoas que entrarão no plano e se a contratação será familiar, MEI ou empresarial. Com essas informações é possível verificar alternativas compatíveis com o seu perfil.'],
    ['A cotação tem compromisso?', 'Você pode pedir informações e analisar as propostas antes de decidir. A contratação só ocorre após a sua escolha e a confirmação das condições.']
  ])}</div></section>
  <section class="section contact-section" id="contato"><div class="container contact-card"><div><p class="eyebrow eyebrow-light">VAMOS CONVERSAR?</p><h2>Seu próximo passo pode ser mais simples.</h2><p>Fale sobre o que você procura e receba orientação para comparar planos de saúde em Fortaleza.</p></div><div class="contact-action">${phone ? button('Falar com Ana Maria', quoteMessage, 'button button-cream') : '<p class="contact-pending">O WhatsApp será ativado assim que o número de atendimento for informado.</p>'}<small>Atendimento personalizado • Fortaleza, CE</small></div></div></section>`;

function detailPage({ path, eyebrow, title, description, intro, profile, bullets, compare, localHeading, localText, questions, related }) {
  const { highlight, badge } = detailHeroContent[path];
  const body = `
    <section class="inner-hero"><div class="container"><nav class="breadcrumbs" aria-label="Você está aqui"><a href="/">Início</a><span aria-hidden="true">/</span><span>${eyebrow}</span></nav><div class="inner-hero-grid"><div class="inner-hero-copy"><p class="eyebrow eyebrow-light"><svg class="hero-pin" viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M12 22s7-7.1 7-13a7 7 0 1 0-14 0c0 5.9 7 13 7 13Z" fill="currentColor"/><circle cx="12" cy="9" r="2.5" fill="#07525b"/></svg>${eyebrow.toUpperCase()} EM FORTALEZA</p><h1>${title.replace(highlight, `<em>${highlight}</em>`)}</h1><p class="inner-hero-lead">${intro}</p>${button('Solicitar cotação', `Olá, Ana Maria! Gostaria de cotar ${eyebrow.toLowerCase()} em Fortaleza.`)}</div><div class="inner-hero-visual"><span class="inner-hero-swoosh" aria-hidden="true"></span><picture class="inner-hero-family"><source media="(max-width: 699px)" srcset="/assets/familia-fortaleza-mobile.webp"><img src="/assets/familia-fortaleza.webp" alt="" width="1536" height="1024" fetchpriority="high"></picture><img class="inner-hero-character" src="/assets/ana-maria-hero.webp" alt="" width="1055" height="1490" fetchpriority="high"><div class="inner-hero-speech"><p>Oi!<br><strong>Conte comigo <span aria-hidden="true">♥</span></strong></p><p>Vamos comparar<br>com mais clareza?</p></div><div class="inner-hero-badge"><span class="badge-icon" aria-hidden="true">✳</span><span>${badge}<br><strong>Escolha com informação.</strong></span></div></div></div></div></section>
    <section class="section detail-intro"><div class="container detail-grid"><div><p class="eyebrow">ENTENDA A MODALIDADE</p><h2>${profile.heading}</h2></div><div><p>${profile.text}</p>${check(bullets)}</div></div></section>
    <section class="section compare-section"><div class="container"><div class="section-heading"><div><p class="eyebrow">COMPARE COM ATENÇÃO</p><h2>O que observar na proposta?</h2></div><p>Valores e regras podem mudar entre operadoras e produtos. Confirme sempre os detalhes da oferta antes da contratação.</p></div><div class="compare-grid">${compare.map((item, index) => `<article><span>0${index + 1}</span><h3>${item[0]}</h3><p>${item[1]}</p></article>`).join('')}</div></div></section>
    <section class="section detail-location"><div class="container detail-location-inner"><p class="eyebrow">ATENDIMENTO LOCAL</p><h2>${localHeading}</h2><p>${localText}</p></div></section>
    <section class="section faq-section"><div class="container faq-grid"><div><p class="eyebrow">DÚVIDAS FREQUENTES</p><h2>Perguntas sobre ${eyebrow.toLowerCase()} em Fortaleza e no Ceará.</h2><p>Use essas respostas como ponto de partida e confira as condições específicas da proposta.</p></div>${faq(questions)}</div></section>
    <section class="section detail-related"><div class="container"><p class="eyebrow">OUTRAS POSSIBILIDADES</p><h2>Explore outras formas de contratação.</h2><div class="related-grid">${related.map((item) => `<a href="${item.href}"><span>${item.label}</span><span aria-hidden="true">↗</span></a>`).join('')}</div></div></section>
    <section class="section contact-section" id="contato"><div class="container contact-card"><div><p class="eyebrow eyebrow-light">FALE COM ANA MARIA</p><h2>Encontre opções para o seu perfil.</h2><p>Conte o que você procura e compare planos de saúde disponíveis em Fortaleza.</p></div><div class="contact-action">${phone ? button('Pedir cotação', `Olá, Ana Maria! Gostaria de cotar ${eyebrow.toLowerCase()} em Fortaleza.`, 'button button-cream') : '<p class="contact-pending">O WhatsApp será ativado assim que o número de atendimento for informado.</p>'}<small>Atendimento personalizado • Fortaleza, CE</small></div></div></section>`;
  return shell({ path, title: description.title, description: description.meta, body });
}

const pages = [
  { path: home, html: shell({ path: home, title: 'Planos de Saúde no Ceará e Fortaleza | Ana Maria', description: 'Compare planos de saúde no Ceará e em Fortaleza para família, MEI e empresa. Entenda cobertura, rede, carência e solicite sua cotação online.', body: homeBody, image: true }) },
  { path: family, html: detailPage({ path: family, eyebrow: 'Plano de saúde familiar', title: 'Plano de saúde familiar em Fortaleza e no Ceará: compare opções.', description: { title: 'Plano de Saúde Familiar em Fortaleza e no Ceará | Ana Maria', meta: 'Compare plano de saúde familiar em Fortaleza e no Ceará. Avalie rede, cobertura, faixas etárias e regras para dependentes antes de cotar.' }, intro: 'Compare alternativas de plano de saúde familiar em Fortaleza e no Ceará, considerando as necessidades da família, as idades e os locais de atendimento importantes para vocês.', profile: { heading: 'Cuidado para as pessoas que fazem parte da sua vida.', text: 'Um plano familiar pode reunir beneficiários conforme as regras de contratação do produto. Antes de escolher, vale listar quem utilizará o plano e quais serviços e locais de atendimento são importantes para cada pessoa.' }, bullets: ['Informe a quantidade de pessoas e as faixas etárias.', 'Considere hospitais, clínicas e laboratórios relevantes para sua família.', 'Confira as regras de inclusão de dependentes no produto escolhido.'], compare: [['Rede credenciada', 'Verifique a rede correspondente ao produto específico e se atende às suas preferências em Fortaleza ou na cidade onde pretende usar o plano.'], ['Cobertura e acomodação', 'Analise os serviços contratados e a opção de acomodação hospitalar quando aplicável.'], ['Carências e custos', 'Confira mensalidade, reajustes previstos, carências e eventual coparticipação.']], localHeading: 'Plano familiar em Fortaleza e em outras cidades do Ceará', localText: 'A rede e os locais de atendimento variam conforme o produto e a cidade. Informe onde sua família pretende usar o plano para verificar as alternativas disponíveis e confirme os prestadores da rede antes da contratação.', questions: [['Quem pode entrar em um plano familiar?', 'As regras de inclusão de dependentes variam conforme a operadora e o produto. Informe a composição da família para avaliar as alternativas disponíveis.'], ['O valor muda conforme a idade?', 'A faixa etária pode influenciar o valor da mensalidade. Confira a tabela e as regras de reajuste da proposta antes de contratar.'], ['É possível escolher hospitais específicos?', 'Você pode informar quais hospitais são importantes para sua família. A presença deles deve ser confirmada na rede do produto contratado, pois redes podem variar.'], ['Há plano familiar em outras cidades do Ceará?', 'A disponibilidade de produtos e da rede varia conforme o município. Informe a cidade onde sua família pretende usar o plano para consultar as opções disponíveis.']], related: [{ href: company, label: 'Plano de saúde empresarial' }, { href: mei, label: 'Plano de saúde para MEI' }] }) },
  { path: company, html: detailPage({ path: company, eyebrow: 'Plano de saúde empresarial', title: 'Plano de saúde empresarial em Fortaleza e no Ceará.', description: { title: 'Plano de Saúde Empresarial em Fortaleza e no Ceará | Ana Maria', meta: 'Compare planos empresariais em Fortaleza e no Ceará para sócios, colaboradores e dependentes. Consulte elegibilidade, rede e cobertura para sua empresa.' }, intro: 'Compare opções de plano de saúde empresarial em Fortaleza e no Ceará de acordo com o perfil da equipe e as regras de cada produto.', profile: { heading: 'Uma decisão que envolve pessoas e planejamento.', text: 'A contratação empresarial pode atender empresas de diferentes portes, conforme os critérios de cada produto. Informações sobre CNPJ, quantidade de vidas e perfil dos beneficiários ajudam a encontrar propostas pertinentes.' }, bullets: ['Defina quantas pessoas poderão participar e seus perfis.', 'Avalie a abrangência necessária para a rotina da equipe.', 'Compare regras de inclusão, permanência e custos do contrato.'], compare: [['Elegibilidade', 'Confira tempo de CNPJ, número mínimo de vidas e documentos exigidos na modalidade ofertada.'], ['Rede e abrangência', 'Considere onde a equipe trabalha e quais locais de atendimento fazem sentido.'], ['Modelo de custos', 'Analise mensalidade, coparticipação, reajustes e condições contratuais.']], localHeading: 'Plano empresarial em Fortaleza e em outras cidades do Ceará', localText: 'A rede, a abrangência e as condições podem mudar conforme o município, a operadora e o produto. Informe onde os beneficiários trabalham e pretendem utilizar o plano para verificar as alternativas adequadas à empresa.', questions: [['Toda empresa pode contratar um plano empresarial?', 'A elegibilidade depende das regras da operadora e do produto, incluindo documentos e número de beneficiários.'], ['É possível incluir dependentes dos colaboradores?', 'Alguns produtos permitem a inclusão conforme regras próprias. Confira parentesco aceito, prazos e condições de adesão na proposta.'], ['Como pedir uma cotação empresarial?', 'Tenha em mãos o CNPJ, a quantidade de pessoas, as faixas etárias e a cidade de atendimento desejada. Esses dados ajudam a identificar propostas disponíveis.'], ['A rede empresarial é igual em todo o Ceará?', 'A rede e a abrangência dependem do produto contratado e da região. Informe os municípios importantes para a equipe e confirme os prestadores disponíveis na proposta.']], related: [{ href: family, label: 'Plano de saúde familiar' }, { href: mei, label: 'Plano de saúde para MEI' }] }) },
  { path: mei, html: detailPage({ path: mei, eyebrow: 'Plano de saúde para MEI', title: 'Plano de saúde para MEI em Fortaleza e no Ceará: compare opções.', description: { title: 'Plano de Saúde para MEI em Fortaleza e no Ceará | Ana Maria', meta: 'Compare planos de saúde para MEI em Fortaleza e no Ceará. Confira elegibilidade, beneficiários, rede e condições antes de solicitar uma cotação.' }, intro: 'Se você é microempreendedor individual, veja como comparar opções em Fortaleza e no Ceará e confira as regras ligadas ao seu CNPJ.', profile: { heading: 'Seu negócio também precisa de escolhas bem pensadas.', text: 'Algumas operadoras oferecem modalidades empresariais acessíveis a MEI. A disponibilidade depende de critérios como tempo de CNPJ, número de beneficiários e documentação exigida por cada produto.' }, bullets: ['Confira os critérios de elegibilidade para seu CNPJ.', 'Verifique se há número mínimo de beneficiários.', 'Compare a rede e o custo total para as pessoas incluídas.'], compare: [['Regras para MEI', 'Confirme tempo mínimo de CNPJ, documentação e composição do grupo exigidos pela proposta.'], ['Cobertura e rede', 'Veja se os serviços e prestadores disponíveis atendem à sua rotina em Fortaleza ou na cidade onde usará o plano.'], ['Custos e prazos', 'Analise mensalidade, coparticipação, carências e regras de reajuste.']], localHeading: 'Opções para MEI em Fortaleza e em outras cidades do Ceará', localText: 'As opções empresariais para MEI e a rede de atendimento podem variar entre municípios e produtos. Informe seu município e confira os critérios de contratação e os locais de atendimento indicados na proposta.', questions: [['MEI pode contratar plano de saúde?', 'Pode haver opções empresariais para MEI, desde que os critérios de elegibilidade da operadora e do produto sejam cumpridos.'], ['Preciso incluir outra pessoa?', 'O número mínimo de beneficiários varia. Confira as condições de cada oferta antes de decidir.'], ['O plano para MEI tem carência?', 'As regras de carência dependem da proposta e das condições aplicáveis. Solicite essa informação por escrito ao comparar alternativas.'], ['Quais informações são necessárias para cotar?', 'Informe o CNPJ, a cidade, as idades e quem pretende incluir no plano. Esses dados ajudam a verificar as opções e regras disponíveis para seu perfil.']], related: [{ href: family, label: 'Plano de saúde familiar' }, { href: company, label: 'Plano de saúde empresarial' }] }) }
];

await mkdir('dist/assets', { recursive: true });
await cp('src/assets', 'dist/assets', { recursive: true });
await writeFile('dist/assets/hero-speech.svg', speechBubbleSvg(), 'utf8');
await cp('src/site.css', 'dist/assets/site.css');
await cp('src/site.js', 'dist/assets/site.js');
await cp('google61c658cc4a703905.html', 'dist/google61c658cc4a703905.html');
for (const page of pages) {
  const dir = join('dist', page.path === '/' ? '' : page.path.slice(1));
  await mkdir(dir, { recursive: true });
  await writeFile(join(dir, 'index.html'), page.html, 'utf8');
}
await writeFile('dist/robots.txt', `User-agent: *\nAllow: /\n${siteUrl ? `Sitemap: ${siteUrl}/sitemap.xml\n` : ''}`, 'utf8');
if (siteUrl) {
  const sitemap = `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${pages.map((page) => `  <url><loc>${esc(siteUrl + page.path)}</loc></url>`).join('\n')}\n</urlset>\n`;
  await writeFile('dist/sitemap.xml', sitemap, 'utf8');
} else await rm('dist/sitemap.xml', { force: true });
console.log(`Geradas ${pages.length} páginas em dist/.${siteUrl ? ' Sitemap e canonicals incluídos.' : ' Configure siteUrl para gerar sitemap e canonicals.'}${phone ? '' : ' Configure whatsapp para ativar as cotações.'}`);
